### ISSUE TITLE
Decide how to respond to RH Description limit for updateinfo

### ISSUE THREAD

**Issue by jcpunk** [rpm-software-management/rpm-metadata#4]
https://access.redhat.com/errata/RHSA-2024:5363 had the following text instead of a description:

```
Errata Tool Automation could not update the description because it is longer (4803) than ET limit of 4000 characters. (OSCI-6058)
Please update the description manually.
```

Should we set a similar upper bound on `description` or ignore it?

**Comment by Conan-Kudo** [comment]
That seems like an ET problem, is there a reason to enforce a description character limit?

**Comment by jcpunk** [comment]
I think we should probably ignore it, but it was a data point from "live in the world"
